name: flutter_touch_spin
description: Simple number input spinner Widget for Flutter. Inspired by Bootstrap Touchspin
version: 2.0.0-nullsafety.0
homepage: https://github.com/danvick

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

